package SSP;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_packet.proto

public final class Proto {
  private Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface packetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:packet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 TYPE = 1;</code>
     */
    int getTYPE();

    /**
     * <code>uint64 num = 2;</code>
     */
    long getNum();

    /**
     * <code>uint64 old = 3;</code>
     */
    long getOld();

    /**
     * <code>uint64 ack = 4;</code>
     */
    long getAck();

    /**
     * <code>uint64 throwaway = 5;</code>
     */
    long getThrowaway();

    /**
     * <code>uint32 diff_index = 6;</code>
     */
    int getDiffIndex();

    /**
     * <code>string diff_appendix = 7;</code>
     */
    java.lang.String getDiffAppendix();
    /**
     * <code>string diff_appendix = 7;</code>
     */
    com.google.protobuf.ByteString
        getDiffAppendixBytes();
  }
  /**
   * Protobuf type {@code packet}
   */
  public  static final class packet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:packet)
      packetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use packet.newBuilder() to construct.
    private packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private packet() {
      tYPE_ = 0;
      num_ = 0L;
      old_ = 0L;
      ack_ = 0L;
      throwaway_ = 0L;
      diffIndex_ = 0;
      diffAppendix_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private packet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              tYPE_ = input.readUInt32();
              break;
            }
            case 16: {

              num_ = input.readUInt64();
              break;
            }
            case 24: {

              old_ = input.readUInt64();
              break;
            }
            case 32: {

              ack_ = input.readUInt64();
              break;
            }
            case 40: {

              throwaway_ = input.readUInt64();
              break;
            }
            case 48: {

              diffIndex_ = input.readUInt32();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              diffAppendix_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Proto.internal_static_packet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Proto.internal_static_packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Proto.packet.class, Proto.packet.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int tYPE_;
    /**
     * <code>uint32 TYPE = 1;</code>
     */
    public int getTYPE() {
      return tYPE_;
    }

    public static final int NUM_FIELD_NUMBER = 2;
    private long num_;
    /**
     * <code>uint64 num = 2;</code>
     */
    public long getNum() {
      return num_;
    }

    public static final int OLD_FIELD_NUMBER = 3;
    private long old_;
    /**
     * <code>uint64 old = 3;</code>
     */
    public long getOld() {
      return old_;
    }

    public static final int ACK_FIELD_NUMBER = 4;
    private long ack_;
    /**
     * <code>uint64 ack = 4;</code>
     */
    public long getAck() {
      return ack_;
    }

    public static final int THROWAWAY_FIELD_NUMBER = 5;
    private long throwaway_;
    /**
     * <code>uint64 throwaway = 5;</code>
     */
    public long getThrowaway() {
      return throwaway_;
    }

    public static final int DIFF_INDEX_FIELD_NUMBER = 6;
    private int diffIndex_;
    /**
     * <code>uint32 diff_index = 6;</code>
     */
    public int getDiffIndex() {
      return diffIndex_;
    }

    public static final int DIFF_APPENDIX_FIELD_NUMBER = 7;
    private volatile java.lang.Object diffAppendix_;
    /**
     * <code>string diff_appendix = 7;</code>
     */
    public java.lang.String getDiffAppendix() {
      java.lang.Object ref = diffAppendix_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        diffAppendix_ = s;
        return s;
      }
    }
    /**
     * <code>string diff_appendix = 7;</code>
     */
    public com.google.protobuf.ByteString
        getDiffAppendixBytes() {
      java.lang.Object ref = diffAppendix_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        diffAppendix_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (tYPE_ != 0) {
        output.writeUInt32(1, tYPE_);
      }
      if (num_ != 0L) {
        output.writeUInt64(2, num_);
      }
      if (old_ != 0L) {
        output.writeUInt64(3, old_);
      }
      if (ack_ != 0L) {
        output.writeUInt64(4, ack_);
      }
      if (throwaway_ != 0L) {
        output.writeUInt64(5, throwaway_);
      }
      if (diffIndex_ != 0) {
        output.writeUInt32(6, diffIndex_);
      }
      if (!getDiffAppendixBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, diffAppendix_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (tYPE_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, tYPE_);
      }
      if (num_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, num_);
      }
      if (old_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, old_);
      }
      if (ack_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, ack_);
      }
      if (throwaway_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, throwaway_);
      }
      if (diffIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, diffIndex_);
      }
      if (!getDiffAppendixBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, diffAppendix_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Proto.packet)) {
        return super.equals(obj);
      }
      Proto.packet other = (Proto.packet) obj;

      boolean result = true;
      result = result && (getTYPE()
          == other.getTYPE());
      result = result && (getNum()
          == other.getNum());
      result = result && (getOld()
          == other.getOld());
      result = result && (getAck()
          == other.getAck());
      result = result && (getThrowaway()
          == other.getThrowaway());
      result = result && (getDiffIndex()
          == other.getDiffIndex());
      result = result && getDiffAppendix()
          .equals(other.getDiffAppendix());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getTYPE();
      hash = (37 * hash) + NUM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNum());
      hash = (37 * hash) + OLD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOld());
      hash = (37 * hash) + ACK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAck());
      hash = (37 * hash) + THROWAWAY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getThrowaway());
      hash = (37 * hash) + DIFF_INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getDiffIndex();
      hash = (37 * hash) + DIFF_APPENDIX_FIELD_NUMBER;
      hash = (53 * hash) + getDiffAppendix().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Proto.packet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Proto.packet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Proto.packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Proto.packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Proto.packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Proto.packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Proto.packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Proto.packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Proto.packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Proto.packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Proto.packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Proto.packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Proto.packet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code packet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:packet)
        Proto.packetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Proto.internal_static_packet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Proto.internal_static_packet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Proto.packet.class, Proto.packet.Builder.class);
      }

      // Construct using Proto.packet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        tYPE_ = 0;

        num_ = 0L;

        old_ = 0L;

        ack_ = 0L;

        throwaway_ = 0L;

        diffIndex_ = 0;

        diffAppendix_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Proto.internal_static_packet_descriptor;
      }

      public Proto.packet getDefaultInstanceForType() {
        return Proto.packet.getDefaultInstance();
      }

      public Proto.packet build() {
        Proto.packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Proto.packet buildPartial() {
        Proto.packet result = new Proto.packet(this);
        result.tYPE_ = tYPE_;
        result.num_ = num_;
        result.old_ = old_;
        result.ack_ = ack_;
        result.throwaway_ = throwaway_;
        result.diffIndex_ = diffIndex_;
        result.diffAppendix_ = diffAppendix_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Proto.packet) {
          return mergeFrom((Proto.packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Proto.packet other) {
        if (other == Proto.packet.getDefaultInstance()) return this;
        if (other.getTYPE() != 0) {
          setTYPE(other.getTYPE());
        }
        if (other.getNum() != 0L) {
          setNum(other.getNum());
        }
        if (other.getOld() != 0L) {
          setOld(other.getOld());
        }
        if (other.getAck() != 0L) {
          setAck(other.getAck());
        }
        if (other.getThrowaway() != 0L) {
          setThrowaway(other.getThrowaway());
        }
        if (other.getDiffIndex() != 0) {
          setDiffIndex(other.getDiffIndex());
        }
        if (!other.getDiffAppendix().isEmpty()) {
          diffAppendix_ = other.diffAppendix_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Proto.packet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Proto.packet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int tYPE_ ;
      /**
       * <code>uint32 TYPE = 1;</code>
       */
      public int getTYPE() {
        return tYPE_;
      }
      /**
       * <code>uint32 TYPE = 1;</code>
       */
      public Builder setTYPE(int value) {
        
        tYPE_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 TYPE = 1;</code>
       */
      public Builder clearTYPE() {
        
        tYPE_ = 0;
        onChanged();
        return this;
      }

      private long num_ ;
      /**
       * <code>uint64 num = 2;</code>
       */
      public long getNum() {
        return num_;
      }
      /**
       * <code>uint64 num = 2;</code>
       */
      public Builder setNum(long value) {
        
        num_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 num = 2;</code>
       */
      public Builder clearNum() {
        
        num_ = 0L;
        onChanged();
        return this;
      }

      private long old_ ;
      /**
       * <code>uint64 old = 3;</code>
       */
      public long getOld() {
        return old_;
      }
      /**
       * <code>uint64 old = 3;</code>
       */
      public Builder setOld(long value) {
        
        old_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 old = 3;</code>
       */
      public Builder clearOld() {
        
        old_ = 0L;
        onChanged();
        return this;
      }

      private long ack_ ;
      /**
       * <code>uint64 ack = 4;</code>
       */
      public long getAck() {
        return ack_;
      }
      /**
       * <code>uint64 ack = 4;</code>
       */
      public Builder setAck(long value) {
        
        ack_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 ack = 4;</code>
       */
      public Builder clearAck() {
        
        ack_ = 0L;
        onChanged();
        return this;
      }

      private long throwaway_ ;
      /**
       * <code>uint64 throwaway = 5;</code>
       */
      public long getThrowaway() {
        return throwaway_;
      }
      /**
       * <code>uint64 throwaway = 5;</code>
       */
      public Builder setThrowaway(long value) {
        
        throwaway_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 throwaway = 5;</code>
       */
      public Builder clearThrowaway() {
        
        throwaway_ = 0L;
        onChanged();
        return this;
      }

      private int diffIndex_ ;
      /**
       * <code>uint32 diff_index = 6;</code>
       */
      public int getDiffIndex() {
        return diffIndex_;
      }
      /**
       * <code>uint32 diff_index = 6;</code>
       */
      public Builder setDiffIndex(int value) {
        
        diffIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 diff_index = 6;</code>
       */
      public Builder clearDiffIndex() {
        
        diffIndex_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object diffAppendix_ = "";
      /**
       * <code>string diff_appendix = 7;</code>
       */
      public java.lang.String getDiffAppendix() {
        java.lang.Object ref = diffAppendix_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          diffAppendix_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string diff_appendix = 7;</code>
       */
      public com.google.protobuf.ByteString
          getDiffAppendixBytes() {
        java.lang.Object ref = diffAppendix_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          diffAppendix_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string diff_appendix = 7;</code>
       */
      public Builder setDiffAppendix(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        diffAppendix_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string diff_appendix = 7;</code>
       */
      public Builder clearDiffAppendix() {
        
        diffAppendix_ = getDefaultInstance().getDiffAppendix();
        onChanged();
        return this;
      }
      /**
       * <code>string diff_appendix = 7;</code>
       */
      public Builder setDiffAppendixBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        diffAppendix_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:packet)
    }

    // @@protoc_insertion_point(class_scope:packet)
    private static final Proto.packet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Proto.packet();
    }

    public static Proto.packet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<packet>
        PARSER = new com.google.protobuf.AbstractParser<packet>() {
      public packet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new packet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<packet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<packet> getParserForType() {
      return PARSER;
    }

    public Proto.packet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_packet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_packet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022proto_packet.proto\"{\n\006packet\022\014\n\004TYPE\030\001" +
      " \001(\r\022\013\n\003num\030\002 \001(\004\022\013\n\003old\030\003 \001(\004\022\013\n\003ack\030\004 " +
      "\001(\004\022\021\n\tthrowaway\030\005 \001(\004\022\022\n\ndiff_index\030\006 \001" +
      "(\r\022\025\n\rdiff_appendix\030\007 \001(\tB\007B\005Protob\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_packet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_packet_descriptor,
        new java.lang.String[] { "TYPE", "Num", "Old", "Ack", "Throwaway", "DiffIndex", "DiffAppendix", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
